import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Field, Form, Formik } from "formik";
import TextFormField from "./components/FormFields/TextFormField";
import SelectFormField from "./components/FormFields/SelectFormField";
import SliderFormField from "./components/FormFields/SliderFormField";
import * as yup from "yup";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const schema = yup.object({
    username: yup.string().required().min(3),
    email: yup.string().email(),
  });
  return (
    <>
      <Head>
        <title>Formik-Best-Practices</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Formik
          initialValues={{ username: "" }}
          onSubmit={(data) => {
            console.log(data);
          }}
        >
          {() => (
            <Form>
              <Field name="username" id="username" component={TextFormField} />
              <Field
                options={[
                  { label: "Dog", value: "dog" },
                  { label: "Cat", value: "cat" },
                ]}
                label="Pet"
                name="pet"
                component={SelectFormField}
              />
              <Field label="Age" name="age" component={SliderFormField} />
            </Form>
          )}
        </Formik>
      </main>
    </>
  );
}
